# Generated by Django 2.2.13 on 2020-08-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200817_2210'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlescope',
            table='articlescope',
        ),
    ]
